### ISSUE TITLE
Basic Minimap No Longer Respects Mouse-button Assignments

### ISSUE THREAD

**Issue by MarkKehn** [funkydude/BasicMinimap#41] opened 2020-02-06 01:00 UTC
This has been going on for little more than a week now. I think I first noticed it after the last game update where Blizzard was planning on fixing the AH issue.

Basic Minimap no longer accepts my chosen mouse-button assignment. No matter what I assign it to it ignores it. I want the Calendar to open on middle-mouse button click but it opens on your default right-click. I want the Tracking set to right-mouse button click but it opens on your default middle-button click.

It shows my correct assignment for the mouse-buttons in the config window but actually clicking on the minimap with the mouse it's using your default assignments.

**Comment by funkydude** [comment] 2020-02-10 19:25
Sounds like a duplicate of #42

**Closed by funkydude** 2020-02-10 19:25 UTC
