### ISSUE TITLE
New size is too small

### ISSUE THREAD

**Issue by malikoth** [funkydude/BasicMinimap#11] opened 2018-08-06 08:44 UTC
I'm playing at 2560x1440, and with the minimap set to its maximum size, it's still far smaller than is comfortable for me, and now I have to lean way closer to my screen to discern any detail from the minimap.  The size option is great, but I do not think it should have replaced scaling, just supplemented it.  Just my $0.02.  :)  Great, simple, functional, elegant addon.  Thanks!

**Comment by funkydude** [comment] 2018-08-06 10:46
At a guess, you've enabled system wide UI scale and set it as some low value, I suggest disabling UI scale all together.

I've tested it at the exact same resolution and the default size looks fine, increasing it makes it look massive, so I cannot reproduce your issue.

**Comment by malikoth** [comment] 2018-08-06 15:58
![malikoth-ui](https://user-images.githubusercontent.com/2665937/43727167-7374caf2-995e-11e8-9cd7-0df9e194e901.png)

Attached is a screenshot of my UI.  Is this the same as what you see?  i.e., do you and I just have different opinions on what a good size is, or is there a difference between what you and I are seeing?  I have measured the width of the minimap with a physical ruler held up to my monitor, and it's 2.7 inches at maximum size.

As you can see in that screenshot, I have System > Advanced > UI Scale disabled.  Ironically, enabling that actually made it bigger, though only just slightly, and moving the slider had no effect whatsoever.

**Comment by tyrantclyr** [comment] 2018-08-06 17:46
Sorry my English is poor.
The same problem that whether the minimap size changed or zooms it in/out, the minimap UI such as character arrow and the other icons are still too small and these icons size did not change.

**Comment by malikoth** [comment] 2018-08-06 21:21
Yes, that's another aspect that makes this harder to use now than before.  The icon size makes a big difference in my ability to glean data from the minimap easily.

**Comment by funkydude** [comment] 2018-08-06 23:10
Fixed in be25685206a9f4b952378d548627fa5e8f85c611

**Closed by funkydude** 2018-08-06 23:10 UTC

**Comment by malikoth** [comment] 2018-08-07 03:45
Thank you so much!  This afternoon, my wife told me that her minimap was broken because it was too small, and I linked her straight here to this issue.  Two minutes later, you released a2816c2 (or it made its way to the Twitch client, not sure what the deployment process looks like).  She reloaded her UI, fixed her map, and said, "This is perfect, this is even better than before.  Please tell the addon author that I love it, and it's perfect!"  So, message relayed.  <3
