### ISSUE TITLE
Feature request: coordinates toggle

### ISSUE THREAD

**Issue by layday** [funkydude/BasicMinimap#37] opened 2019-09-16 14:35 UTC
Unless I missed it (and that does tend to happen), I don't think there's an option to hide the new coordinates display, if you would consider it.

**Comment by funkydude** [comment] 2019-09-16 15:05
Duplicate of #32

**Closed by funkydude** 2019-09-16 15:05 UTC

**Comment by layday** [comment] 2019-09-16 15:13
Whoops, sorry.
