### ISSUE TITLE
Lua errors... 

### ISSUE THREAD

**Issue by Finrodi** [funkydude/BasicMinimap#24] opened 2019-08-10 09:46 UTC
Didnt have any problems yesterday but actually redid ui and got a bunch of errors now..

```
Message: Interface\AddOns\BasicMinimap\BasicMinimap.lua:305: Attempt to register unknown event "CALENDAR_UPDATE_PENDING_INVITES"
Time: Sat Aug 10 11:44:51 2019
Count: 1
Stack: Interface\AddOns\BasicMinimap\BasicMinimap.lua:305: Attempt to register unknown event "CALENDAR_UPDATE_PENDING_INVITES"
[C]: in function `RegisterEvent'
Interface\AddOns\BasicMinimap\BasicMinimap.lua:305: in main chunk

Locals: (*temporary) = BasicMinimap {
 0 = <userdata>
 HideButtons = <function> defined @Interface\AddOns\BasicMinimap\BasicMinimap.lua:36
 ADDON_LOADED = <function> defined @Interface\AddOns\BasicMinimap\BasicMinimap.lua:41
 CALENDAR_UPDATE_PENDING_INVITES = <function> defined @Interface\AddOns\BasicMinimap\BasicMinimap.lua:297
 PLAYER_LOGIN = <function> defined @Interface\AddOns\BasicMinimap\BasicMinimap.lua:94
 CALENDAR_ACTION_PENDING = <function> defined @Interface\AddOns\BasicMinimap\BasicMinimap.lua:297
 blizzButtonPositions = <table> {
 }
}
(*temporary) = "CALENDAR_UPDATE_PENDING_INVITES"
```

```Message: Interface\AddOns\BasicMinimap\BasicMinimap.lua:298: attempt to index global 'C_Calendar' (a nil value)
Time: Sat Aug 10 11:44:56 2019
Count: 1
Stack: Interface\AddOns\BasicMinimap\BasicMinimap.lua:298: attempt to index global 'C_Calendar' (a nil value)
Interface\AddOns\BasicMinimap\BasicMinimap.lua:298: in function `CALENDAR_UPDATE_PENDING_INVITES'
Interface\AddOns\BasicMinimap\BasicMinimap.lua:98: in function `?'
Interface\AddOns\BasicMinimap\BasicMinimap.lua:32: in function <Interface\AddOns\BasicMinimap\BasicMinimap.lua:31>

Locals: self = BasicMinimap {
 0 = <userdata>
 HideButtons = <function> defined @Interface\AddOns\BasicMinimap\BasicMinimap.lua:36
 CALENDAR_UPDATE_PENDING_INVITES = <function> defined @Interface\AddOns\BasicMinimap\BasicMinimap.lua:297
 db = <table> {
 }
 CALENDAR_ACTION_PENDING = <function> defined @Interface\AddOns\BasicMinimap\BasicMinimap.lua:297
 blizzButtonPositions = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'C_Calendar' (a nil value)"
frame = BasicMinimap {
 0 = <userdata>
 HideButtons = <function> defined @Interface\AddOns\BasicMinimap\BasicMinimap.lua:36
 CALENDAR_UPDATE_PENDING_INVITES = <function> defined @Interface\AddOns\BasicMinimap\BasicMinimap.lua:297
 db = <table> {
 }
 CALENDAR_ACTION_PENDING = <function> defined @Interface\AddOns\BasicMinimap\BasicMinimap.lua:297
 blizzButtonPositions = <table> {
 }
}
```

Both when logging in, but a bunch more once I go to the options menu like this one (addon not usable right now)

```Message: Interface\AddOns\BasicMinimap_Options\Options.lua:108: attempt to index field 'mask' (a nil value)
Time: Sat Aug 10 11:46:11 2019
Count: 1
Stack: Interface\AddOns\BasicMinimap_Options\Options.lua:108: attempt to index field 'mask' (a nil value)
Interface\AddOns\BasicMinimap_Options\Options.lua:108: in function <Interface\AddOns\BasicMinimap_Options\Options.lua:100>
[C]: ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
[C]: ?
...ace\AddOns\TheClassicRace\libs\AceGUI\AceGUI-3.0.lua:72: in function <...ace\AddOns\TheClassicRace\libs\AceGUI\AceGUI-3.0.lua:70>
...ace\AddOns\TheClassicRace\libs\AceGUI\AceGUI-3.0.lua:287: in function `Fire'
...icRace\libs\AceGUI\widgets\AceGUIWidget-DropDown.lua:442: in function <...icRace\libs\AceGUI\widgets\AceGUIWidget-DropDown.lua:433>
[C]: ?
...ace\AddOns\TheClassicRace\libs\AceGUI\AceGUI-3.0.lua:72: in function <...ace\AddOns\TheClassicRace\libs\AceGUI\AceGUI-3.0.lua:70>
...ace\AddOns\TheClassicRace\libs\AceGUI\AceGUI-3.0.lua:287: in function `Fire'
...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:351: in function <...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:341>

Locals: <none>```

**Comment by funkydude** [comment] 2019-08-10 10:35
I thought it would be obvious but apparently it isn't.
DO NOT report issues with people addons without explicitly stating it's caused by Classic wow unless you take some form of joy in wasting peoples time.

Closing since you're using the live version of BasicMinimap on Classic, instead of using the classic specific version.

**Closed by funkydude** 2019-08-10 10:35 UTC
